on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      which:
        description: 'Which dependents'
        default: 'most'

name: Reverse dependency check v1.1

jobs:
  revdep_check:
    uses: JanMarvin/recheck/.github/workflows/recheck.yml@v1.1
    with:
      # If manual, use input. If PR, default to 'most'.
      which: ${{ github.event.inputs.which || 'most' }}
